// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: tictactoe.proto

package backend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerX       string                 `protobuf:"bytes,1,opt,name=player_x,json=playerX,proto3" json:"player_x,omitempty"`
	PlayerO       string                 `protobuf:"bytes,2,opt,name=player_o,json=playerO,proto3" json:"player_o,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_tictactoe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGameRequest) GetPlayerX() string {
	if x != nil {
		return x.PlayerX
	}
	return ""
}

func (x *CreateGameRequest) GetPlayerO() string {
	if x != nil {
		return x.PlayerO
	}
	return ""
}

type CreateGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	mi := &file_tictactoe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGameResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type MakeMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Player        string                 `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"` // "X" or "O"
	Row           int32                  `protobuf:"varint,3,opt,name=row,proto3" json:"row,omitempty"`
	Col           int32                  `protobuf:"varint,4,opt,name=col,proto3" json:"col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMoveRequest) Reset() {
	*x = MakeMoveRequest{}
	mi := &file_tictactoe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveRequest) ProtoMessage() {}

func (x *MakeMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveRequest.ProtoReflect.Descriptor instead.
func (*MakeMoveRequest) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{2}
}

func (x *MakeMoveRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *MakeMoveRequest) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

func (x *MakeMoveRequest) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *MakeMoveRequest) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

type MakeMoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "success" or "error"
	Board         []string               `protobuf:"bytes,2,rep,name=board,proto3" json:"board,omitempty"`   // flat ["", "", "", "", "", "", "", "", ""]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMoveResponse) Reset() {
	*x = MakeMoveResponse{}
	mi := &file_tictactoe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveResponse) ProtoMessage() {}

func (x *MakeMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveResponse.ProtoReflect.Descriptor instead.
func (*MakeMoveResponse) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{3}
}

func (x *MakeMoveResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MakeMoveResponse) GetBoard() []string {
	if x != nil {
		return x.Board
	}
	return nil
}

type GetGameStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStateRequest) Reset() {
	*x = GetGameStateRequest{}
	mi := &file_tictactoe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStateRequest) ProtoMessage() {}

func (x *GetGameStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStateRequest.ProtoReflect.Descriptor instead.
func (*GetGameStateRequest) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{4}
}

func (x *GetGameStateRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type GetGameStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Board         []string               `protobuf:"bytes,2,rep,name=board,proto3" json:"board,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStateResponse) Reset() {
	*x = GetGameStateResponse{}
	mi := &file_tictactoe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStateResponse) ProtoMessage() {}

func (x *GetGameStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStateResponse.ProtoReflect.Descriptor instead.
func (*GetGameStateResponse) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{5}
}

func (x *GetGameStateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetGameStateResponse) GetBoard() []string {
	if x != nil {
		return x.Board
	}
	return nil
}

var File_tictactoe_proto protoreflect.FileDescriptor

const file_tictactoe_proto_rawDesc = "" +
	"\n" +
	"\x0ftictactoe.proto\"I\n" +
	"\x11CreateGameRequest\x12\x19\n" +
	"\bplayer_x\x18\x01 \x01(\tR\aplayerX\x12\x19\n" +
	"\bplayer_o\x18\x02 \x01(\tR\aplayerO\"-\n" +
	"\x12CreateGameResponse\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"f\n" +
	"\x0fMakeMoveRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x16\n" +
	"\x06player\x18\x02 \x01(\tR\x06player\x12\x10\n" +
	"\x03row\x18\x03 \x01(\x05R\x03row\x12\x10\n" +
	"\x03col\x18\x04 \x01(\x05R\x03col\"@\n" +
	"\x10MakeMoveResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05board\x18\x02 \x03(\tR\x05board\".\n" +
	"\x13GetGameStateRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"D\n" +
	"\x14GetGameStateResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05board\x18\x02 \x03(\tR\x05board2\xb0\x01\n" +
	"\ttictactoe\x125\n" +
	"\n" +
	"CreateGame\x12\x12.CreateGameRequest\x1a\x13.CreateGameResponse\x12/\n" +
	"\bMakeMove\x12\x10.MakeMoveRequest\x1a\x11.MakeMoveResponse\x12;\n" +
	"\fGetGameState\x12\x14.GetGameStateRequest\x1a\x15.GetGameStateResponseB\"Z github.com/MustangThumbi/backendb\x06proto3"

var (
	file_tictactoe_proto_rawDescOnce sync.Once
	file_tictactoe_proto_rawDescData []byte
)

func file_tictactoe_proto_rawDescGZIP() []byte {
	file_tictactoe_proto_rawDescOnce.Do(func() {
		file_tictactoe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tictactoe_proto_rawDesc), len(file_tictactoe_proto_rawDesc)))
	})
	return file_tictactoe_proto_rawDescData
}

var file_tictactoe_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tictactoe_proto_goTypes = []any{
	(*CreateGameRequest)(nil),    // 0: CreateGameRequest
	(*CreateGameResponse)(nil),   // 1: CreateGameResponse
	(*MakeMoveRequest)(nil),      // 2: MakeMoveRequest
	(*MakeMoveResponse)(nil),     // 3: MakeMoveResponse
	(*GetGameStateRequest)(nil),  // 4: GetGameStateRequest
	(*GetGameStateResponse)(nil), // 5: GetGameStateResponse
}
var file_tictactoe_proto_depIdxs = []int32{
	0, // 0: tictactoe.CreateGame:input_type -> CreateGameRequest
	2, // 1: tictactoe.MakeMove:input_type -> MakeMoveRequest
	4, // 2: tictactoe.GetGameState:input_type -> GetGameStateRequest
	1, // 3: tictactoe.CreateGame:output_type -> CreateGameResponse
	3, // 4: tictactoe.MakeMove:output_type -> MakeMoveResponse
	5, // 5: tictactoe.GetGameState:output_type -> GetGameStateResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tictactoe_proto_init() }
func file_tictactoe_proto_init() {
	if File_tictactoe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tictactoe_proto_rawDesc), len(file_tictactoe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tictactoe_proto_goTypes,
		DependencyIndexes: file_tictactoe_proto_depIdxs,
		MessageInfos:      file_tictactoe_proto_msgTypes,
	}.Build()
	File_tictactoe_proto = out.File
	file_tictactoe_proto_goTypes = nil
	file_tictactoe_proto_depIdxs = nil
}
